### ISSUE TITLE
Issue with the "classification.py" script

### ISSUE THREAD

**Issue by Vincev454** [SegataLab/metaml#1]
Hello there,

When trying to reproduce the wiki example, i got the following error:

`Traceback (most recent call last):
  File "classification.py", line 296, in <module>
    skf = StratifiedKFold(l.iloc[i_u.values.T[j],0], runs_cv_folds, shuffle=True, random_state=j)
TypeError: __init__() got multiple values for keyword argument 'shuffle'`

Any help would be appreciated.
Best,
Vince

**Comment by edoardopasolli** [comment]
Please use the file "classification_thomas-manghi.py" instead of "classification.py" that you find in the same folder. It fixes some dependencies
